version: 1
accounts:
- name: alice
  coins:
  - 10000ctz
  - 20zusd
  - 200000000stake
- name: vault
  coins:
  - 100000zusd
  - 100000000stake
- name: carol
  coins:
  - 10000cqt
  - 10zusd
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: vault
  coins:
  - 5zusd
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
